Fix/minor
polaris-hub/auroris pull request #4
Opened 2024-05-17 02:58 UTC by zhu0619

## Changelogs

- Added data_path in Curator export if available.
- Fix Curator serialization for ordered steps.
- Add extenstion to display pydantic docstring in documentation page.
- Update Auroris documentation.
- Minor fixes. 

---

_Checklist:_

- [ ] _Was this PR discussed in an issue? It is recommended to first discuss a new feature into a GitHub issue before opening a PR._
- [ ] _Add tests to cover the fixed bug(s) or the newly introduced feature(s) (if appropriate)._
- [ ] _Update the API documentation if a new function is added, or an existing one is deleted._
- [ ] _Write concise and explanatory changelogs above._
- [ ] _If possible, assign one of the following labels to the PR: `feature`, `fix` or `test` (or ask a maintainer to do it for you)._

---

_discussion related to that PR_

2024-05-17 10:18 UTC, cwognum requested changes
Thanks @zhu0619! I left some comments. I have been quite nitpicky, but I think it's important to be very intentional and careful in the decisions we make early and the example we set. This will simplify our lives later on. I made an effort to explain all my considerations.

2024-05-17 10:18 UTC, cwognum commented on auroris/curation/actions/_ac_stereoisomer.py
> +                has_cliff = dataset[col_with_prefix].__eq__(True)
I believe

```py
dataset[col_with_prefix].__eq__(True)
```

is the same as 

```py
dataset[col_with_prefix] == True
```

is the same as 
```py
dataset[col_with_prefix]
```

2024-05-17 10:18 UTC, cwognum commented on auroris/curation/actions/_mol.py
> +    PretrainedHFTransformer = None
General tip: Also good to be as precise as possible when catching exceptions. 

```suggestion
try:
    from molfeat.trans.pretrained.hf_transformers import PretrainedHFTransformer
except ImportError:
    PretrainedHFTransformer = None
```

2024-05-17 10:18 UTC, cwognum commented on auroris/curation/_curator.py
> +            pd.read_csv(value, nrows=5)
I would suggest we use `.parquet`. This is consistent with Polaris and I think is generally speaking good practice. Or both?

2024-05-17 10:18 UTC, cwognum commented on auroris/curation/actions/_mol.py
> +                )
I understand the desire for custom embeddings, but I am not a big fan of adding an (optional) `molfeat` dependency. This can get complex quick and is not part of what's core to what we're trying to offer with `auroris`. 

For example, with the current implementation, the exact same curation workflow won't return the same result depending on whether or not you have `molfeat` installed, which hinders reproducibility - Reproducibility is core to `auroris`. 

How about we do the following instead: The import dataset can contain custom embeddings?

The `input_column` in this step thus either specifies:
1. A SMILES column or a RDKit Mol column. In that case we simply use standard ECFP embeddings. 
2. A column with NumPy array features. In that case we will use the embeddings in that column. 

That way, users have full flexibility over how to get those embeddings, e.g. through Molfeat.

2024-05-17 13:57 UTC, zhu0619 commented on auroris/curation/_curator.py
> +        data["steps"] = steps
The default dictionary output from `model_dump` doesn't respect the specified order of the steps list. And this causes issue if reload `from_json`. 
There might be better alternatives that I am not aware of from pydantic?

2024-05-17 13:59 UTC, zhu0619 commented on auroris/curation/_curator.py
> +        serialization["steps"] = [{step.name: step.model_dump()} for step in self.steps]
The default dictionary output from model_dump doesn't respect the specified order of the steps list. And this causes issue if reload from_json.
There might be better alternatives that I am not aware of from pydantic?

2024-05-17 14:02 UTC, zhu0619 commented on auroris/curation/_curator.py
> +        data["steps"] = steps
In my test, although the json can be loaded correctly, but the content is just incorrect.

2024-05-17 14:09 UTC, zhu0619 commented on auroris/curation/actions/_ac_stereoisomer.py
> +                has_cliff = dataset[col_with_prefix].__eq__(True)
It's for the formatting and lint issue. Of course, the last option would work.

2024-05-17 14:14 UTC, zhu0619 commented on env.yml
> +    - griffe_fieldz
What I have is there is nothing about attributes and description for the action classes.

2024-05-17 14:18 UTC, zhu0619 commented on auroris/visualization/_distribution.py
> +    plt.title(title)
I have simplied this plot to single plot. Of course, we can still use `create_figure`.

2024-05-17 14:20 UTC, zhu0619 commented on auroris/utils.py
> +        return os.path.relpath(path, destination)
Good to know. I wasn't aware of `get_protocol`.

2024-05-17 14:25 UTC, zhu0619 commented on auroris/utils.py
> +            return path.replace("gs://", "https://storage.googleapis.com/")
I added this to make my life easier to export images and reports directly to GCP while working on the polaris recipe. We can remove it once we decide to move away from GCP completely.

2024-05-17 14:32 UTC, zhu0619 commented on auroris/report/broadcaster/_html.py
> +                    filename = re.sub(r"[^\w\-\.]", "_", image.title) if image.title else image_counter
Make sense. I can add the counter as well.

2024-05-17 14:34 UTC, zhu0619 commented on auroris/report/_report.py
> +            image = ipyimg2img(image_or_figure)
I will test this out.

2024-05-17 14:34 UTC, zhu0619 commented on auroris/utils.py
> +            f.write(image_bytes)
That was my first attempt. 
Does it work on your end?

2024-05-17 14:45 UTC, zhu0619 commented on auroris/curation/_curator.py
> +        description="List of curation actions. Check all the available action <auroris.curation.actions.__all__>.",
I moved the docs to description because I encountered errors when compiling docs with `mkdocs`.
This is also the reason I had added the extension in mkdocs. 

But I was using `Args` in the docstring instead `Attributes`. Could that be the cause of the error?

2024-05-17 14:52 UTC, zhu0619 commented on auroris/curation/actions/_mol.py
> +                )
That makes sense to me.

2024-05-17 14:58 UTC, zhu0619 commented on auroris/curation/_curator.py
> +            pd.read_csv(value, nrows=5)
`.parquet` is more used for efficiency, which makes sense in polaris Dataset.
The most incoming datasets for curation are more often in `.csv`, `.tsv` etc. 
I would add both.

2024-05-17 19:59 UTC, zhu0619 commented on auroris/report/broadcaster/_logger.py
> +        self.logger.setLevel(logging.INFO)
I understand the formatting purpose. 
However, the debugging level produced many logs which are irrelevant to curation.
For example:
![image](https://github.com/polaris-hub/auroris/assets/6717019/c5eaed98-5f2a-4185-a997-f162dcebd551)
It also happens if rerun some curation steps. 
![image](https://github.com/polaris-hub/auroris/assets/6717019/72ba0b4e-4320-477d-a45c-f93eb9a2b39f)

2024-05-17 20:11 UTC, zhu0619 commented on auroris/report/broadcaster/_logger.py
> +        self.logger.setLevel(logging.INFO)
Do we really need all levels of logging for the report? If not, maybe just replace the style of logging.info to logging.debug in FORMATS ?

2024-05-19 08:06 UTC, cwognum commented on auroris/curation/_curator.py
> +        data["steps"] = steps
Ah, I see now! The problem is that `BaseAction.name` should be a [Pydantic `computed_field`](https://docs.pydantic.dev/2.0/usage/computed_fields/).

So it should be: 

```py
    @computed_field
    @property
    def name(self) -> str:
        """The name of the action. Needs to be unique."""
        return self.__class__.__name__
```

My bad for not adding a test case for this! Should've caught that!

Could you add a test case to check this?

2024-05-19 08:10 UTC, cwognum commented on env.yml
> +    - griffe_fieldz
I figured that would be the case, but I'm not seeing it in the docs. See for example:

<details><summary>Screenshot</summary>
<p>

<img width="904" alt="image" src="https://github.com/polaris-hub/auroris/assets/28000055/85e850fd-b46a-447c-b78a-2ea67e9dd827">

</p>
</details>

2024-05-19 08:16 UTC, cwognum commented on auroris/report/broadcaster/_logger.py
> +        self.logger.setLevel(logging.INFO)
Yes, I think that's a bug of mine! We should double check this, but I think that's because we were changing logging globally, rather than locally:

See [this comment](https://github.com/polaris-hub/auroris/pull/4#discussion_r1604556901) above.

> Do we really need all levels of logging for the report?

No, not really! If the above solution doesn't work, we can also use your solution and just change the formatting.

2024-05-19 08:16 UTC, cwognum commented on auroris/report/broadcaster/_html.py
> +                    filename = re.sub(r"[^\w\-\.]", "_", image.title) if image.title else image_counter
And could you document what the RE does?

2024-05-19 08:29 UTC, cwognum commented on auroris/utils.py
> +            f.write(image_bytes)
Yeah, I tested it again! This is the code I used: 

```py
import fsspec
from PIL import Image

with fsspec.open("https://images.unsplash.com/photo-1608848461950-0fe51dfc41cb", "rb") as f:
    with fsspec.open("gs://polaris-private/curated_datasets/test.png", "wb") as fd: 
        im = Image.open(f)
        im.save(fd, format="png")
```

Two notes: 
- It seems calling `Image.open()` loads the image lazily. If the file would be closed before saving the image again (by exiting the context manager), it would raise a `ValueError: I/O operation on closed file.`. 
- You can get a `ValueError: unknown file extension: `, which can be fixed by setting `format="png"` in `im.save()`

2024-05-19 08:36 UTC, cwognum commented on auroris/utils.py
> +            return path.replace("gs://", "https://storage.googleapis.com/")
I'm all for making your life easier, but for the above-mentioned reasons I would prefer to add code in the `polaris-recipes` repo rather than here. If we add code here, we should be willing to maintain it.

Maybe you could add a small subclass of the `HTMLBroadcaster` in the `polaris-recipes` repo that adds support for GCP images? The `recipes` repo is not meant to be general purpose, so we can more easily scope the function and also make a stronger case when people ask why we're not e.g. extending support for S3 buckets or private bucket as well.

2024-05-19 08:37 UTC, cwognum commented on auroris/curation/_curator.py
> +        description="List of curation actions. Check all the available action <auroris.curation.actions.__all__>.",
Yes, that could be the cause! We render the docs in `strict` mode and if you add `Args` that means it checks whether all args in the docs match the args in the function.

2024-05-19 08:38 UTC, cwognum commented on auroris/curation/actions/_ac_stereoisomer.py
> +                has_cliff = dataset[col_with_prefix].__eq__(True)
> It's for the formatting and lint issue.

What issue??

I would prefer not to call a magic method (i.e. `__eq__`). That always feels a little hacky!

2024-05-19 08:39 UTC, cwognum commented on auroris/curation/_curator.py
> +            pd.read_csv(value, nrows=5)
That makes sense to me!

2024-05-22 14:21 UTC, zhu0619 commented on auroris/curation/_curator.py
> +        data["steps"] = steps
I had added a [test](https://github.com/polaris-hub/auroris/blob/ed7a16e23cb6f255b2864700d5b578be88b317ea/tests/test_curator.py#L13) to check the loaded content.  (print and name file for debugging, and will be fixed later.)

The `computed_field` adds the name of the action to the exported dictionary. 

When I load back directly by 
```
    def from_json(cls, path: str):
        with fsspec.open(path, "r") as f:
            data = json.load(f)
        return cls.model_validate(data)
```
The above unit test raise error in below.
```
        for step1, step2 in zip(curator.steps, curator_reload.steps):
>           assert step1 == step2
E           AssertionError: assert MoleculeCurat...culeCuration') == Deduplication...eduplication')
E             
E             Full diff:
E             - Deduplication(prefix='MOL_', deduplicate_on=None, y_cols=None, keep='first', method='median', name='Deduplication')
E             + MoleculeCuration(prefix='MOL_', input_column='smiles', remove_salt_solvent=True, remove_stereo=False, count_stereoisomers=True, count_stereocenters=True, y_cols=None, fast=True, name='MoleculeCuration')
```
I am not quite understand the behavior of pydantic model_validate here. 
How does the `Deduplication` was initiated which was never in the config.
The exported and reload json dictionary are correct. The error happens at `cls.model_validate`.

2024-05-22 18:30 UTC, zhu0619 commented on auroris/curation/actions/_ac_stereoisomer.py
> +                has_cliff = dataset[col_with_prefix].__eq__(True)
For option `dataset[col_with_prefix] == True`
```
ruff check 
```
error:
```
auroris/curation/actions/_ac_stereoisomer.py:101:29: E712 Avoid equality comparisons to `True`; use `if dataset[col_with_prefix]:` for truth checks
Found 1 error.
```

`__eq__(True)` was a quick fix for that error. I don't have preference to that. 
I will just use `dataset[col_with_prefix]` instead.

2024-05-23 20:47 UTC, cwognum approved these changes

2024-05-23 20:48 UTC, merged